# Generated by Django 3.2.23 on 2024-01-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_graph', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeproperty',
            name='data_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nodetype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='relationshipproperty',
            name='data_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relationshiptype',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
